### ISSUE TITLE
dev branch not working, fails on app.post

### ISSUE THREAD

**Issue by abhishekpsen** [ShwetaRaje23/ShopCast#2]
/home/abhishekpsen/Spring16/MAS/ShopCast/routes/index.js:45
app.post('/api/cast', function(req, res) {
^
ReferenceError: app is not defined
    at Object.<anonymous> (/home/abhishekpsen/Spring16/MAS/ShopCast/routes/index.js:45:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/abhishekpsen/Spring16/MAS/ShopCast/app.js:12:14)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3

**Comment by vedanuj** [comment]
Commented the test code for now.
